name: Deploy Infrastructure

on:
  workflow_dispatch:

concurrency:
  group: "deploy-infrastructure"
  cancel-in-progress: false

permissions: {}

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  WORK_DIR: ./terraform/environment/dev

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}

    steps:
      - name: checkout repository 
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: configure AWS credentials w/ OIDC
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          role-to-assume: ${{ secrets.AWS_INFRA_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: login to ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896

      - name: setup terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85
        with:
          terraform_version: "1.14.7"

      - name: terraform format
        run: terraform fmt -check
        continue-on-error: true

      - name: terraform init
        run: terraform init -input=false

      - name: terraform validate
        run: terraform validate

      - name: security scan 
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf
        with:
          directory: ${{ env.WORK_DIR }}
        continue-on-error: true

      - name: terraform plan
        run: terraform plan -out=tfplan

      - name: terraform apply
        run: terraform apply -input=false tfplan