name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Safety Check: Type "destroy" to confirm teardown'
        required: true
        type: string

concurrency:
  group: "deploy-infrastructure" 
  cancel-in-progress: false

permissions: {}

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  WORK_DIR: ./terraform/environment/dev

jobs:
  teardown-infrastructure:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}

    steps:

      - name: checkout repository 
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: safety lock
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "destroy" ]; then
            echo "Error: You did not type 'destroy'. Infrastructure is safe."
            exit 1
          fi
          echo "Teardown confirmed. Proceeding..."

      - name: configure AWS credentials w/ OIDC
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          role-to-assume: ${{ secrets.AWS_INFRA_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform setup
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85
        with:
          terraform_version: "1.14.7"

      - name: terraform init
        run: terraform init -input=false

      - name: terraform destroy
        run: terraform destroy --auto-approve

      - name: final status dashboard
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Teardown Successful ✅" >> $GITHUB_STEP_SUMMARY
            echo "All AWS resources have been cleanly deleted" >> $GITHUB_STEP_SUMMARY
          else
            echo "Teardown Failed!" >> $GITHUB_STEP_SUMMARY
            echo "Check the Terraform logs above. Some resources might still be running in AWS which may require manual deletion." >> $GITHUB_STEP_SUMMARY
          fi